# Generated by Django 4.2.23 on 2025-08-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(unique=True)),
                ('meal_choice', models.CharField(max_length=200)),
            ],
        ),
    ]
